rootProject.name = 'spring-boot-examples'

include 'projects:command-line-runner'
include 'projects:application-runner'
include 'projects:value-annotation'
include 'projects:scheduled-annotation'
include 'projects:configuration-properties'
include 'projects:swagger-webmvc'
include 'projects:scalar-webmvc'
