rootProject.name = 'spring-boot-examples'

include 'projects:core:command-line-runner'
include 'projects:core:application-runner'
include 'projects:core:value-annotation'
include 'projects:core:scheduled-annotation'
include 'projects:core:configuration-properties'
include 'projects:web:swagger-webmvc'
include 'projects:web:scalar-webmvc'
include 'projects:jpa:jpa-example'
include 'projects:cache:cache-annotation'
