spring:
  main:
    banner-mode: off

first-app:
  name: First Spring Configuration Properties Example
  version: 1.0.0-SNAPSHOT
  environment: development
  port: 8080
  tags: tag1,tag2,tag3
  debug: true

second-app:
  name: Second Spring Configuration Properties Example
  version: 1.0.0
  environment: production
  port: 8443
  tags:
    - tag1
    - tag2
    - tag3
  debug: false
