plugins {
	id 'application-conventions'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.springframework.boot:spring-boot-starter-logging'
}

application {
	mainClass = 'fr.damnardev.spring.example.swaggerwebmvc.Startup'
}
