plugins {
	id 'application-conventions'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
	runtimeOnly 'org.springframework.boot:spring-boot-starter-logging'
}

application {
	mainClass = 'fr.damnardev.spring.example.swaggerrestcontroller.Startup'
}
