services:
  app:
    container_name: sbe-app
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4096M
        reservations:
          cpus: "0.5"
          memory: 4096M
    command: sleep infinity
    restart: unless-stopped