package fr.damnardev.spring.example.scalarwebflux.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import reactor.core.publisher.Mono;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import fr.damnardev.spring.example.scalarwebflux.dto.EmployeeDto;
import fr.damnardev.spring.example.scalarwebflux.dto.EmployeeListDto;
import fr.damnardev.spring.example.scalarwebflux.service.EmployeeService;

@RestController
@RequestMapping("/employees")
@Tag(name = "Employees", description = "Employee management API")
public class EmployeeController {

	private final EmployeeService employeeService;

	public EmployeeController(EmployeeService employeeService) {
		this.employeeService = employeeService;
	}

	@GetMapping
	@Operation(summary = "List employees", description = "Retrieves a paginated list of employees")
	@ApiResponse(responseCode = "200", description = "Paginated list of employees", content = @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeListDto.class)))
	public Mono<ResponseEntity<EmployeeListDto>> getAllEmployees(
			@RequestParam(defaultValue = "0") int page,
			@RequestParam(defaultValue = "10") int size) {
		if (page < 0 || size < 1 || size > EmployeeService.MAX_PAGE_SIZE) {
			return Mono.just(ResponseEntity.badRequest()
										   .build());
		}
		return this.employeeService.getAllEmployees(page, size)
								   .map(ResponseEntity::ok);
	}

	@GetMapping("/{id}")
	@Operation(summary = "Get an employee", description = "Retrieves an employee by its numeric ID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Employee found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeDto.class))),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public Mono<ResponseEntity<EmployeeDto>> getEmployeeById(@PathVariable Long id) {
		return this.employeeService.getEmployeeById(id)
								   .map(ResponseEntity::ok)
								   .defaultIfEmpty(ResponseEntity.notFound()
																 .build());
	}

	@PostMapping
	@Operation(summary = "Create an employee", description = "Creates a new employee. The numeric ID is generated by the database.")
	@ApiResponse(responseCode = "201", description = "Employee created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeDto.class)))
	public Mono<ResponseEntity<EmployeeDto>> createEmployee(@RequestBody EmployeeDto employee) {
		return this.employeeService.createEmployee(employee)
								   .map(createdEmployee -> ResponseEntity.status(HttpStatus.CREATED)
																		 .body(createdEmployee));
	}

	@PutMapping("/{id}")
	@Operation(summary = "Update an employee", description = "Updates an existing employee by its numeric ID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Employee updated", content = @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeDto.class))),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public Mono<ResponseEntity<EmployeeDto>> updateEmployee(@PathVariable Long id, @RequestBody EmployeeDto updatedEmployee) {
		return this.employeeService.updateEmployee(id, updatedEmployee)
								   .map(ResponseEntity::ok)
								   .defaultIfEmpty(ResponseEntity.notFound()
																 .build());
	}

	@DeleteMapping("/{id}")
	@Operation(summary = "Delete an employee", description = "Deletes an employee by its numeric ID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "204", description = "Employee deleted"),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public Mono<ResponseEntity<Void>> deleteEmployee(@PathVariable Long id) {
		return this.employeeService.deleteEmployee(id)
								   .map(removed -> removed ? ResponseEntity.noContent()
																		   .build() : ResponseEntity.notFound()
																									.build());
	}

}
