package fr.damnardev.spring.example.swaggerrestcontroller.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import fr.damnardev.spring.example.swaggerrestcontroller.model.Employee;

@RestController
@RequestMapping("/employees")
@Tag(name = "Employees", description = "Employee Management API")
public class EmployeeController {

	private final List<Employee> employees = new ArrayList<>();

	@GetMapping
	@Operation(summary = "Get all employees", description = "Retrieve a list of all employees")
	@ApiResponse(responseCode = "200", description = "List of employees", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Employee.class)))
	public ResponseEntity<List<Employee>> getAllEmployees() {
		return ResponseEntity.ok(this.employees);
	}

	@GetMapping("/{id}")
	@Operation(summary = "Get employee by ID", description = "Retrieve a specific employee by their UUID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Employee found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Employee.class))),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public ResponseEntity<Employee> getEmployeeById(@PathVariable UUID id) {
		Optional<Employee> employee = this.employees.stream().filter(e -> e.getId().equals(id)).findFirst();
		return employee.map(ResponseEntity::ok)
					   .orElseGet(() -> ResponseEntity.notFound()
													  .build());
	}

	@PostMapping
	@Operation(summary = "Create a new employee", description = "Create a new employee. UUID is auto-generated by the server.")
	@ApiResponse(responseCode = "201", description = "Employee created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Employee.class)))
	public ResponseEntity<Employee> createEmployee(@RequestBody Employee employee) {
		employee.setId(UUID.randomUUID());
		this.employees.add(employee);
		return ResponseEntity.status(HttpStatus.CREATED).body(employee);
	}

	@PutMapping("/{id}")
	@Operation(summary = "Update an employee", description = "Update an existing employee by their UUID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Employee updated", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Employee.class))),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public ResponseEntity<Employee> updateEmployee(@PathVariable UUID id, @RequestBody Employee updatedEmployee) {
		Optional<Employee> employee = this.employees.stream().filter(e -> e.getId().equals(id)).findFirst();
		if (employee.isPresent()) {
			Employee emp = employee.get();
			emp.setFirstName(updatedEmployee.getFirstName());
			emp.setLastName(updatedEmployee.getLastName());
			emp.setBirthday(updatedEmployee.getBirthday());
			return ResponseEntity.ok(emp);
		}
		return ResponseEntity.notFound().build();
	}

	@DeleteMapping("/{id}")
	@Operation(summary = "Delete an employee", description = "Delete an employee by their UUID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "204", description = "Employee deleted"),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public ResponseEntity<Void> deleteEmployee(@PathVariable UUID id) {
		boolean removed = this.employees.removeIf(e -> e.getId().equals(id));
		if (removed) {
			return ResponseEntity.noContent().build();
		}
		return ResponseEntity.notFound().build();
	}

}
