package fr.damnardev.spring.example.swaggerwebmvc.controller;

import java.util.Optional;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import fr.damnardev.spring.example.swaggerwebmvc.dto.EmployeeDto;
import fr.damnardev.spring.example.swaggerwebmvc.dto.EmployeeListDto;
import fr.damnardev.spring.example.swaggerwebmvc.service.EmployeeService;

@RestController
@RequestMapping("/employees")
@Tag(name = "Employees", description = "Employee Management API")
public class EmployeeController {

	private final EmployeeService employeeService;

	public EmployeeController(EmployeeService employeeService) {
		this.employeeService = employeeService;
	}

	@GetMapping
	@Operation(summary = "Get all employees", description = "Retrieve a list of all employees")
	@ApiResponse(responseCode = "200", description = "Paginated list of employees", content = @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeListDto.class)))
	public ResponseEntity<EmployeeListDto> getAllEmployees(
			@RequestParam(defaultValue = "0") int page,
			@RequestParam(defaultValue = "10") int size) {
		if (page < 0 || size < 1 || size > EmployeeService.MAX_PAGE_SIZE) {
			return ResponseEntity.badRequest()
								 .build();
		}
		return ResponseEntity.ok(this.employeeService.getAllEmployees(page, size));
	}

	@GetMapping("/{id}")
	@Operation(summary = "Get employee by ID", description = "Retrieve a specific employee by their numeric ID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Employee found", content = @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeDto.class))),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public ResponseEntity<EmployeeDto> getEmployeeById(@PathVariable Long id) {
		Optional<EmployeeDto> employee = this.employeeService.getEmployeeById(id);
		return employee.map(ResponseEntity::ok)
					   .orElseGet(() -> ResponseEntity.notFound()
													  .build());
	}

	@PostMapping
	@Operation(summary = "Create a new employee", description = "Create a new employee. The numeric ID is generated by the database.")
	@ApiResponse(responseCode = "201", description = "Employee created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeDto.class)))
	public ResponseEntity<EmployeeDto> createEmployee(@RequestBody EmployeeDto employee) {
		return ResponseEntity.status(HttpStatus.CREATED)
							 .body(this.employeeService.createEmployee(employee));
	}

	@PutMapping("/{id}")
	@Operation(summary = "Update an employee", description = "Update an existing employee by their numeric ID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Employee updated", content = @Content(mediaType = "application/json", schema = @Schema(implementation = EmployeeDto.class))),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public ResponseEntity<EmployeeDto> updateEmployee(@PathVariable Long id, @RequestBody EmployeeDto updatedEmployee) {
		return this.employeeService.updateEmployee(id, updatedEmployee)
								   .map(ResponseEntity::ok)
								   .orElseGet(() -> ResponseEntity.notFound()
																  .build());
	}

	@DeleteMapping("/{id}")
	@Operation(summary = "Delete an employee", description = "Delete an employee by their numeric ID")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "204", description = "Employee deleted"),
			@ApiResponse(responseCode = "404", description = "Employee not found")
	})
	public ResponseEntity<Void> deleteEmployee(@PathVariable Long id) {
		boolean removed = this.employeeService.deleteEmployee(id);
		if (removed) {
			return ResponseEntity.noContent()
								 .build();
		}
		return ResponseEntity.notFound()
							 .build();
	}

}
